exports.req_topic_names = {
    REGISTER: 'register_request',
    LOGIN: 'login_request',
    LOGOUT: 'logout_request',
    HOTEL_LISTING: 'hotel_listing_request',
    FLIGHT_LISTING: 'flight_listing_request',
    ADD_FLIGHT: 'addflight_topic',
    ADD_HOTEL: 'addhotel_topic',
    FETCH_HOTELS: 'fetchhotels_topic',
    CHANGE_ROOMS: 'addrooms_topic',
    FETCH_FLIGHTS: 'fetchflights_topic',
    MODIFY_HOTEL: 'modifyhotel_topic',
    MODIFY_FLIGHT: 'modifyflight_topic',
    MODIFY_FLIGHTCLASS: 'modifyflightclass_topic',
    FETCH_CARS: 'fetchcars_topic',
    ADD_CAR: 'addcar_topic',
    MODIFY_CAR: 'modifycar_topic',
    FETCH_HOSTS: 'fetchhosts_topic',
    ADD_HOST: 'addhost_topic',
    MODIFY_HOST: 'modifyhost_topic',
    FETCH_USERS: 'fetchusers_topic',
    MODIFY_USERS: 'modifyusers_topic',
    CAR_LISTING: 'car_listing_topic',
    FETCH_USERPROFILE : 'fetchuserprofile_topic',
    // GET_CHART_DATA : 'getchartdata_topic',
    LOG_ANALYTICS_DATA: 'logAnalyticsData_topic',
    TOP_10_PROPERTIES: 'top10Properties_topic',
    CITY_WISE_REVENUE:'cityWiseRevenue_topic',
    TOP_10_HOSTS: 'top10Hosts_topic',
    REVIEWS_ON_PROPERTIES: 'reviewsOnProperties_topic',
    FETCH_HOTELBOOKINGS : 'fetchhotelbookings_topic',
    FETCH_CARBOOKINGS : 'fetchcarbookings_topic',
    FETCH_FLIGHTBOOKINGS : 'fetchflightbookings_topic',
    LOG_USER_TRACING_TREE : 'logUserTracingTree_topic',
    FETCH_USERTIMEPERPAGE : 'fetchusertimeperpage_topic'
};

//
// exports.res_topic_names = {
//     REGISTER: 'register_response',
//     LOGIN: 'login_response',
//     LOGOUT: 'logout_response',
//     HOTEL_LISTING: 'hotel_listing_response',
//
// };