export const actionTypes = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    SIGN_UP: "SIGN_UP",
    HOTEL_LISTING_SUCCESS: "HOTEL_LISTING_SUCCESS",
    FLIGHT_LISTING_SUCCESS: "FLIGHT_LISTING_SUCCESS",
    FILTER_PRICE_CHANGE: "FILTER_PRICE_CHANGE",
    TOGGLE_BOOKING_TYPE: "TOGGLE_BOOKING_TYPE",
    FLIGHT_ESSENTIALS_ADD: "FLIGHT_ESSENTIALS_ADD",
}