export const actionTypes = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    SIGN_UP: "SIGN_UP",
    HOTEL_LISTING_SUCCESS: "HOTEL_LISTING_SUCCESS",
    FILTER_PRICE_CHANGE: "FILTER_PRICE_CHANGE",
    ADMIN_FLIGHT_LISTING_SUCCESS : "ADMIN_FLIGHT_LISTING_SUCCESS",
    ADMIN_ADD_FLIGHT_SUCCESS : "ADMIN_ADD_FLIGHT_SUCCESS",
    ADMIN_HOTEL_LISTING_SUCCESS : "ADMIN_HOTEL_LISTING_SUCCESS",
    ADMIN_ADD_HOTEL_SUCCESS : "ADMIN_ADD_HOTEL_SUCCESS",
    ADMIN_ADD_CAR_SUCCESS : "ADMIN_ADD_CAR_SUCCESS",
    ADMIN_CAR_LISTING_SUCCESS : "ADMIN_CAR_LISTING_SUCCESS "
    FLIGHT_LISTING_SUCCESS: "FLIGHT_LISTING_SUCCESS",
    TOGGLE_BOOKING_TYPE: "TOGGLE_BOOKING_TYPE",
    FLIGHT_ESSENTIALS_ADD: "FLIGHT_ESSENTIALS_ADD",
}